### PR TITLE
Update offline.json for Including VulnerableApp Project

### PR DESCRIPTION
**Pull request by preetkaran20**

### CODE REVIEW

**Comment by kingthorin** [comment]
Updates should be made against the source repo: https://github.com/OWASP/OWASP-VWAD

They are then pushed here.

**Comment by kingthorin** [comment]
I’ll update the README of this repo to clarify for future contributors.

**Comment by preetkaran20** [comment]
sure will do the change there. thanks

**Comment by kingthorin** [comment]
Thank you!

**Comment by preetkaran20** [comment]
Hi @kingthorin ,
please review https://github.com/OWASP/OWASP-VWAD/pull/84

**Pull request closed without merging**
