### PR TITLE
Add GitHub stars badge for offline applications

### PR DESCRIPTION
**Pull request by bkimminich**
(Redundantly stored in app.badge property. Only added for a couple applications so far.)

### CODE REVIEW

**Comment by bkimminich** [comment]
⚠️ Not tested locally
⚠️ Only added `badge` property for Juice Shop and some others from the top of the list

**Comment by bkimminich** [comment]
It's a "Hey, take a look and if everybody likes it, either me or some other poor fellow can complete the JSON stuff" kind of PR... 😁

**Comment by kingthorin** [comment]
Fair enough!  I like it, I'm sure it can be tackled 👍

**Comment by bkimminich** [comment]
Of course the smarter solution would be to look for occurences of `github.com` in either name or references and then extract the relevant part for the shield. But that was beyond my Jekyll skillz and willingness to deviate from Juice Shop work here at the Projects Summit... 😆

**Comment by bkimminich** [comment]
I'll add the `badge` label to all entries now and also empty ones and ping you once it's finished so you can backport it into the original repo, okay?

**Comment by kingthorin** [comment]
Sure if you’ve got time and interest. I had figured I was gonna have you o tackle it later 👍

**Comment by bkimminich** [comment]
Done for all offline apps! If you can test it locally that'd be great, otherwise feel free to merge and see what happens. I can't test locally on my Chromebook here in 🇲🇽 unfortunately.

**Comment by kingthorin** [comment]
I’m not aware of a way to test the new www-* stuff locally. But I’m willing to see how/if it breaks. Will merge it shortly.

**Comment by kingthorin** [comment]
Success!
image

Thanks @bkimminich !

**Pull request merged**
