### PR TITLE
Adding new vulnerability site to owasp

### PR DESCRIPTION
**Pull request by yrprey**
We recently launched a vulnerability and pentest site and want to add it to the owasp collection

### CODE REVIEW

**Comment by psiinon** [comment]
Also, you have a Flash video on the site??
Why???
Flash was disabled in browsers many years ago, hardly anyone will be able to view it...

**Comment by yrprey** [comment]
The https://yrprey.com is not a vulnerable application, but a page or landing page that promotes or markets vulnerable applications that are available on GitHub. On GitHub, the user can download the container version for Docker or download the source code and create it in their own local environment. The user has two download options. 

The https://yrprey.com page only advertises or promotes the vulnerable application, which is available on Github.

The address to download source-code is: 

https://github.com/yrprey/yrprey-backend

https://github.com/yrprey/yrprey-frontend

And versão container is: https://github.com/yrprey/yrprey-application

You understand me?

**Comment by kingthorin** [comment]
https://github.com/OWASP/OWASP-VWAD/pull/204

**Comment by vagnermengali** [comment]
I have already uploaded it to the repository

**Pull request closed without merging**
